# Site settings
title: XingguoHuang
description: xingguohuang
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Xingguo Huang
user_description: I have had the honor to serve as a faculty for many prestigious universities, including Harvard, UW, and UVA, in hope of bringing all the different ideologies and cultures together. Initially inspired by many great breakthroughs of modern educational technology, I got to experience many wonderful moments as an educator. Now as a career changer, inspired by the same dream, I firmly believe that we can achieve even more with the power of technology. I am passionate about different approaches to increasing productivity in and out of the learning environment.
user_title: Aspiring Software Developer | Seeking Entry-Level Position | Graduating in September 2023
email: huang.xingg@northeastern.edu
twitter_username: lorem_ipsum
github_username: https://github.com/xingguo-huang
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
